version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm test
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - '**/*'
post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id "E3UORLOTWWVERB" --paths /index.html /* /static/* /favicon.ico
